name: Checkov CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローン
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'

      # Checkovをインストール
      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      # Checkovを実行
      - name: Run Checkov
        run: |
          checkov -d ./terraform/  # 対象ディレクトリを指定
