# This is an example reuse of the reusable Checkov workflow that can be copied and pasted to repositories that should use it.
# Prior to using, ensure that the GitHub Organization and repo name are accurate (and not MyGitHubOrganizationName/github-workflows).
name: checkov-scan

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkov-scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      contents: read # for actions/checkout to fetch code
    secrets: inherit
    uses: MyGitHubOrganizationName/github-workflows/.github/workflows/checkov-source.yaml@main
